import type { Theme } from "./Theme";

export class NordTheme implements Theme {
    bg_color_primary = "#2B303C";
    bg_color_secondary = "#2E3440";
    bg_color_tertiary = "#252A34";
    bg_color_quaternary = "#3B4252";
    bg_color_primary_unfocused = "#2B303C";
    bg_color_secondary_unfocused = "#303643";
    bg_color_tertiary_unfocused = "#252A34";
    bg_color_quaternary_unfocused = "#3B4252";
    fg_color_primary = "#FFFFFF";
    fg_color_secondary = "#C4CAD5";
    fg_color_tertiary = "";
    fg_color_quaternary = "";
    fg_color_primary_unfocused = "#777F84";
    fg_color_secondary_unfocused = "#717684";
    fg_color_tertiary_unfocused = "";
    fg_color_quaternary_unfocused = "";
    border_color_primary = "#262a35";
    border_color_secondary = "";
    border_color_tertiary = "";
    border_color_quaternary = "";
    border_color_primary_unfocused = "";
    border_color_secondary_unfocused = "";
    border_color_tertiary_unfocused = "";
    border_color_quaternary_unfocused = "";
    selection_fg_color = "";
    selection_bg_color = "";
    selection_unfocused_fg_color = "";
    selection_unfocused_bg_color = "";
    warning_color = "";
    error_color = "";
    success_color = "";
    input_fg_color = "#DFDFDF";
    input_bg_color = "#2B303C";
    input_border_color = "#262A35";
    input_hover_fg_color = "#F8F8F8";
    input_hover_bg_color = "#3F4758";
    input_hover_border_color = "#262A35";
    input_active_fg_color = "#FFFFFF";
    input_active_bg_color = "#495266";
    input_active_border_color = "#262A35";
}
